version: 2
    node:
        container_name: chat-project_${VERSION}
        env_file:
          - docker-compose.env
        image: chat-project_node:${VERSION}
        ports:
            - "${PORT_NODE}:1234"
