import React from "react";
import { storiesOf } from "@storybook/react";
import Example from "../components/Example";
import FooterMobile from "../components/footer/FooterMobile";
import FooterDesktop from "../components/footer/FooterDesktop";
import FullCheckbox from "../components/icons/FullCheckbox";
import EmptyCheckbox from "../components/icons/EmptyCheckbox";
import RadioFull from "../components/icons/RadioFull";
import RadioEmpty from "../components/icons/RadioEmpty";
import Cogs from "../components/icons/Cogs";
import EuroSign from "../components/icons/EuroSign";
import IdBadge from "../components/icons/IdBadge";
import Phone from "../components/icons/Phone";
import Place from "../components/icons/Place";
import Power from "../components/icons/Power";
import Email from "../components/icons/Email";
import "../main.css";

storiesOf("Example", module).add("example", () => <Example />);
storiesOf("Icons", module).add("full checkbox", () => <FullCheckbox />);
storiesOf("Icons", module).add("empty checkbox", () => <EmptyCheckbox />);
storiesOf("Icons", module).add("full radio", () => <RadioFull />);
storiesOf("Icons", module).add("empty radio", () => <RadioEmpty />);
storiesOf("Icons", module).add("cogs", () => <Cogs />);
storiesOf("Icons", module).add("euro sign", () => <EuroSign />);
storiesOf("Icons", module).add("id badge", () => <IdBadge />);
storiesOf("Icons", module).add("phone", () => <Phone />);
storiesOf("Icons", module).add("place", () => <Place />);
storiesOf("Icons", module).add("power", () => <Power />);
storiesOf("Icons", module).add("email", () => <Email />);
storiesOf("Footer", module).add("mobile footer", () => <FooterMobile />);
storiesOf("Footer", module).add("desktop footer", () => <FooterDesktop />);
