import React from "react";
import { storiesOf } from "@storybook/react";
import Example from "../components/Example";
import "../style/index.css";
import "../style/fonts.css";

storiesOf("Example", module).add("example", () => <Example />);
storiesOf("Icons", module).add("full checkbox", () => <FullCheckbox />);
storiesOf("Icons", module).add("empty checkbox", () => <EmptyCheckbox />);
storiesOf("Icons", module).add("full radio", () => <RadioFull />);
storiesOf("Icons", module).add("empty radio", () => <RadioEmpty />);
storiesOf("Icons", module).add("cogs", () => <Cogs />);
storiesOf("Icons", module).add("euro sign", () => <EuroSign />);
storiesOf("Icons", module).add("id badge", () => <IdBadge />);
storiesOf("Icons", module).add("phone", () => <Phone />);
storiesOf("Icons", module).add("place", () => <Place />);
storiesOf("Icons", module).add("power", () => <Power />);
storiesOf("Icons", module).add("email", () => <Email />);
storiesOf("Footer", module).add("mobile footer", () => <FooterMobile />);
storiesOf("Footer", module).add("desktop footer", () => <FooterDesktop />);
